apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: roberts3
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: roberts3/hw4image:latest
        ports:
          - name: http-port
            containerPort: 80
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "53cretP@ss"
        - name: MYSQL_DATABASE
          value: csc468
