CREATE DATABASE IF NOT EXISTS csc468;
USE csc468;

CREATE TABLE IF NOT EXISTS cattle (
    id INT AUTO_INCREMENT PRIMARY KEY,
    color VARCHAR(255),
    horns VARCHAR(255)
);

LOAD DATA INFILE '/var/lib/mysql-files/cattle.csv'
INTO TABLE cattle
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(color, horns);
